plugins {
    id 'eclipse'
    id 'idea'
    id 'java-library'
    id 'net.neoforged.moddev'
}

def conventions = extensions.create('conventions', ConventionsExtension)

ext.buildnumber = 0
project.buildnumber = System.getenv('BUILD_NUMBER') ?: 'custom'

if (System.getenv('GHA_RELEASE_WORKFLOW')) {
    version = "${mod_version}"
} else if (System.getenv('GITHUB_RUN_NUMBER')) {
    project.buildnumber = System.getenv('GITHUB_RUN_NUMBER')
    version = "${mod_version}-${release_type}+${buildnumber}-gha"
} else {
    project.buildnumber = System.getenv('BUILD_NUMBER') ?: 'custom'
    version = "${mod_version}-${release_type}+${buildnumber}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    exclude 'testing/**'
}

neoForge {
    version = project.neo_version

    accessTransformers = [rootProject.file("src/main/resources/META-INF/accesstransformer.cfg")]
}

repositories {
    maven {
        url = 'https://maven.gegy.dev/releases'
        content {
            includeGroup 'org.lovetropics'
            includeGroup 'com.tterrag.registrate'
            includeGroup 'eu.pb4'
        }
    }
    maven {
        url = 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
    maven {
        name = 'CurseMaven'
        url = 'https://www.cursemaven.com'
        content {
            includeGroup('curse.maven')
        }
    }
}

dependencies {
    implementation "org.lovetropics:LTLib:$ltlib_version"
    // TODO: HACK - We get Registrate at runtime through JarJar from Tropicraft. We should rather prefer to depend on the slim jar.
    compileOnly "com.tterrag.registrate:Registrate:MC26.2-${registrate_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << "-Xmaxerrs" << "100000"
}

tasks.register('sourceJar', Jar) {
    dependsOn classes
    archiveClassifier = 'sources'
    from sourceSets.main.java
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.withType(ProcessResources).configureEach {
    outputs.upToDateWhen { false }
}

var replaceProperties = project.provider {
    [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : conventions.modId.get(),
            mod_version            : mod_version,
    ]
}

var generateModMetadata = project.tasks.register('generateModMetadata', ProcessResources) {
    def properties = replaceProperties.get()
    inputs.properties properties
    expand properties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}
project.sourceSets.main.resources.srcDir generateModMetadata

project.neoForge.ideSyncTask generateModMetadata

abstract class ConventionsExtension {
    private final Project project

    ConventionsExtension(Project project) {
        this.project = project
    }

    abstract Property<String> getModId()
}
