plugins {
    id 'net.neoforged.moddev' version '2.0.141'
    id 'conventions'
}

group = 'org.lovetropics'
base {
    archivesName = 'LTMinigames'
}

sourceSets.test.resources {
    srcDir 'src/generated/resources'
    include 'testing/**'
    include 'data/ltminigames/structure/**'
}

def mod_id = 'ltminigames'

conventions {
    modId = mod_id
}

neoForge {
    addModdingDependenciesTo sourceSets.test

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
        "${mod_id}_test" {
            sourceSet sourceSets.main
            sourceSet sourceSets.test
        }
        "ltgames_lobbies" {
            sourceSet project(':lobbies').sourceSets.main
        }
    }

    runs {
        client {
            client()
            loadedMods = [mods."${mod_id}", mods.ltgames_lobbies]

            programArguments.addAll '--username', 'Dev###'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        server {
            server()
            loadedMods = [mods."${mod_id}", mods.ltgames_lobbies]

            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            sourceSet = sourceSets.test
            loadedMods = [mods."${mod_id}_test"]

            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        data {
            clientData()
            loadedMods = [mods."${mod_id}_test"]

            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            logLevel = org.slf4j.event.Level.INFO
            ideName = project.name + " - " + ideName.get()
            jvmArgument("-Dmixin.debug.export=true")
        }
    }
}

dependencies {
    runtimeOnly 'maven.modrinth:tropicraft:9.11.0+26.2'

    jarJar(runtimeOnly(project(':lobbies')))
    testImplementation project(':lobbies')

    jarJar("com.tterrag.registrate:Registrate:MC26.2-${registrate_version}") {
        version {
            strictly "[MC26.2-${registrate_version},MC26.3)"
            prefer "MC26.2-${registrate_version}"
        }
    }

    jarJar("org.lovetropics:LTLib:$ltlib_version")

    runtimeOnly "org.lovetropics:LTExtras:$ltextras_version"

    jarJar(compileOnly("org.lovetropics:peekaboo-api:$peekaboo_version"))
    runtimeOnly("org.lovetropics:peekaboo:$peekaboo_version") {
        transitive = false
    }

    runtimeOnly "org.lovetropics:lt-multimedia:$multimedia_version"

    testImplementation platform("org.junit:junit-bom:5.7.0")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
