import net.neoforged.moddevgradle.dsl.ModModel

plugins {
    id 'net.neoforged.moddev' version '2.0.141'
    id 'eclipse'
    id 'idea'
    id 'java-library'
}

group = 'org.lovetropics'
base {
    archivesName = 'LTMinigames'
}

def env = System.getenv()
if (env.GITHUB_RUN_NUMBER) {
    version = "$mod_version.${env.GITHUB_RUN_NUMBER}"
} else {
    version = "$mod_version.0-SNAPSHOT"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

/*
Additional modules to add to the project, for splitting features up.
By default the modules will have access to the main source set, minecraft, and add libraries.
*/
ext {
    splitModules = [
            'lobbies'
    ]
}

for (String name : splitModules) {
    sourceSets.create(name, {
        java {
            srcDir "src/${name}/java"
        }
        resources {
            srcDir "src/${name}/resources"
            srcDir "src/generated/resources/ltgames_${name}"
        }
    })
}

sourceSets.test.resources {
//    srcDir 'src/generated/resources'
    include 'testing/**'
    include 'data/ltminigames/structure/**'
}

sourceSets.main.resources {
    srcDir 'src/generated/resources/ltminigames'
    exclude 'testing/**'
}

def mod_id = 'ltminigames'

configurations {
    libImplementation
    libCompileOnly
    implementation.extendsFrom libImplementation
    compileOnly.extendsFrom libCompileOnly
}

for (String name : splitModules) {
    def sourceSet = sourceSets.named(name).get()
    def libImplementation = configurations.named("libImplementation").get()
    def libCompileOnly = configurations.named("libCompileOnly").get()
    configurations.named(sourceSet.implementationConfigurationName).get().extendsFrom libImplementation
    configurations.named(sourceSet.compileOnlyConfigurationName).get().extendsFrom libCompileOnly
}

neoForge {
    version = project.neo_version
    accessTransformers = [project.file("src/main/resources/META-INF/accesstransformer.cfg")]

    addModdingDependenciesTo sourceSets.test

    List<ModModel> defaultModsToLoad = new ArrayList<>()
    for (String name : splitModules) {
        def sourceSet = sourceSets.named(name)
        addModdingDependenciesTo(sourceSet.get())
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
        "${mod_id}_test" {
            sourceSet sourceSets.main
            sourceSet sourceSets.test
        }
    }

    mods.named(mod_id, {
        for (String name : splitModules) {
            def sourceSet = sourceSets.named(name)
            it.sourceSet(sourceSet.get())
        }
    })


    defaultModsToLoad.add(mods.named(mod_id).get())

    runs {
        client {
            client()
            loadedMods = defaultModsToLoad
            programArguments.addAll '--username', 'Dev###'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        server {
            server()
            loadedMods.addAll defaultModsToLoad
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            sourceSet = sourceSets.test

            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        data {
            clientData()
            loadedMods.addAll defaultModsToLoad
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()

            // Todo fix this part
            for (String name : splitModules) {
                programArguments.addAll('--mod', 'ltgames_' + name, '--existing', file("src/${name}/resources/").absolutePath)
            }
        }

        configureEach {
            logLevel = org.slf4j.event.Level.INFO
            ideName = project.name + " - " + ideName.get()
            jvmArgument("-Dmixin.debug.export=true")
        }
    }

}

repositories {
    maven {
        url = 'https://maven.gegy.dev/releases'
        content {
            includeGroup 'org.lovetropics'
            includeGroup 'com.tterrag.registrate'
            includeGroup 'eu.pb4'
        }
    }
    maven {
        url = 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
    maven {
        name = 'CurseMaven'
        url = 'https://www.cursemaven.com'
        content {
            includeGroup('curse.maven')
        }
    }
}

dependencies {
    jarJar(libImplementation "org.lovetropics:LTLib:$ltlib_version")
    jarJar(libCompileOnly "org.lovetropics:peekaboo-api:$peekaboo_version")
    libCompileOnly "com.tterrag.registrate:Registrate:MC26.2-${registrate_version}"

    runtimeOnly 'maven.modrinth:tropicraft:9.11.0+26.2'
    runtimeOnly("org.lovetropics:peekaboo:$peekaboo_version") {
        transitive = false
    }
    runtimeOnly "org.lovetropics:lt-multimedia:$multimedia_version"
    runtimeOnly "org.lovetropics:LTExtras:$ltextras_version"

    // TODO: HACK - We get Registrate at runtime through JarJar from Tropicraft. We should rather prefer to depend on the slim jar.
    jarJar("com.tterrag.registrate:Registrate:MC26.2-${registrate_version}") {
        version {
            strictly "[MC26.2-${registrate_version},MC26.3)"
            prefer "MC26.2-${registrate_version}"
        }
    }

    testImplementation platform("org.junit:junit-bom:5.7.0")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"

    for (String module : splitModules) {
        runtimeOnly sourceSets.named(module).get().output
        "${sourceSets.named(module).get().implementationConfigurationName}" sourceSets.main.output
        testImplementation sourceSets.named(module).get().output
    }
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}


tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << "-Xmaxerrs" << "100000"
}

tasks.register('sourceJar', Jar) {
    dependsOn classes
    archiveClassifier = 'sources'
    from sourceSets.main.java
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}


tasks.withType(ProcessResources).configureEach {
    outputs.upToDateWhen { false }
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}
sourceSets.main.resources.srcDir generateModMetadata

neoForge.ideSyncTask generateModMetadata


tasks.withType(Copy) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}


tasks.named('jar', Jar, { jar ->
    from([sourceSets.main.output])
    for (String name : splitModules) {
        def sourceSet = sourceSets.named(name)
        jar.from(sourceSet.get().output)
    }
})
