mod_id=ltminigames
mod_version=26.2
release_type=alpha
minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
loader_version_range=[4,)
neo_version=26.2.0.57
neo_version_range=[26.2.0.57-beta,)

registrate_version=1.6.0
ltlib_version=[26.2,26.3)
ltextras_version=[26.2,26.3)
peekaboo_version=1.0.0+26.2
multimedia_version=[0.1.46,0.2)

org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
