modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/LoveTropics/LTMinigames/issues"
license="ARR"

[[mods]]
modId="ltminigames"
version="${file.jarVersion}"
displayName="LTMinigames" #mandatory
displayURL="https://lovetropics.com"
#logoFile="examplemod.png" #optional
credits="" #optional
authors="Cojomax99, tterrag, kingbdogz" #optional
description='''
Minigame engine for the LoveTropics livestream event.
'''

[[mods]]
modId="weather2"
version="${file.jarVersion}"
displayName="Weather2"
logoFile="itcrowd.png"
authors="Corosus"
description='''

'''