modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/LoveTropics/LTMinigames/issues"
license="ARR"

[[mods]]
modId="ltminigames"
version="$mod_version"
displayName="LTMinigames" #mandatory
displayURL="https://lovetropics.com"
#logoFile="examplemod.png" #optional
credits="" #optional
authors="Cojomax99, tterrag, kingbdogz" #optional
description='''
Minigame engine for the LoveTropics livestream event.
'''
