name: Run game tests

on:
  push:
  pull_request:
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened

jobs:

  jdk21:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Run game tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ltminigames_gametestServer
